name: dartling_form
version: 0.0.1
author: Your Name
description: dartling_form application that uses dartling for its model.
homepage: http://ondart.me/
dependencies:
  browser: any
  dartling:
    git: git://github.com/dzenanr/dartling.git
  dartling_default_app:
    git: git://github.com/dzenanr/dartling_default_app.git
  web_ui: any
